import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Poppins({ weight: ["200","400", "600","700"], subsets: ["latin"] });
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/page";
import { Toaster } from "@/components/ui/toaster"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
    

  
      <body className={inter.className}>
      <ThemeProvider attribute="class" disableTransitionOnChange    defaultTheme="dark"
            enableSystem
            
          >
         <Navbar/>     
        {children}
          <Toaster/>
        <Footer/>
        </ThemeProvider>
        </body>
      
    </html>
  );
}
